name: "Prod env"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Apply"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_WORKSPACE: "prod"

      - name: Terraform Workspace
        id: workspace
        run: terraform workspace select prod
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
